export function TermsOfService() {
  return (
    <div className="min-h-screen bg-black text-gray-200 font-mono p-8 max-w-4xl mx-auto">
      <div className="mb-8">
        <a href="/" className="text-green-400 hover:text-green-300 text-sm">← Back</a>
      </div>
      <h1 className="text-2xl font-bold text-white mb-2">Terms of Service</h1>
      <p className="text-gray-500 text-sm mb-8">Last updated: March 19, 2026</p>

      <div className="border border-yellow-600 bg-yellow-900/20 rounded p-4 mb-8">
        <p className="text-yellow-400 text-sm font-bold">⚠ NOT FINANCIAL ADVICE</p>
        <p className="text-yellow-200 text-sm mt-1">
          WorldState provides intelligence signals for research and informational purposes only.
          Nothing on this platform constitutes investment advice, a solicitation to buy or sell
          any security, or a recommendation to take any specific investment action.
          Always consult a qualified financial advisor before making investment decisions.
        </p>
      </div>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-green-400 mb-3">1. Acceptance</h2>
        <p className="text-sm text-gray-300">By accessing WorldState, you agree to these Terms. If you do not agree, do not use the service. These Terms constitute a binding agreement between you and WorldState.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-green-400 mb-3">2. Permitted Use</h2>
        <ul className="space-y-2 text-sm text-gray-300 list-disc list-inside">
          <li>Research, analysis, and situational awareness for internal business use</li>
          <li>Academic and journalistic research</li>
          <li>Risk management and compliance monitoring</li>
        </ul>
        <p className="mt-3 text-sm text-gray-400">You may <strong className="text-white">not</strong> use WorldState to: provide investment advice to third parties, automate trading decisions, or resell raw data feeds.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-green-400 mb-3">3. No Financial Advice Disclaimer</h2>
        <p className="text-sm text-gray-300">WorldState is not a registered investment adviser under the Investment Advisers Act of 1940, or any equivalent legislation in other jurisdictions. Strategy signals, cluster analyses, and market commentary generated by WorldState are produced by automated systems and artificial intelligence, have not been reviewed by licensed financial professionals, and have not been backtested against historical market data. Past performance of any signal or strategy is not indicative of future results.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-green-400 mb-3">4. Intellectual Property</h2>
        <p className="text-sm text-gray-300">The WorldState platform, including all software, algorithms, and visual design, is proprietary. You receive a limited, non-exclusive, non-transferable licence to access the service during your subscription. Source data from third parties (Reuters, EDGAR, Finnhub) remains subject to their respective licences.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-green-400 mb-3">5. Rate Limits & Fair Use</h2>
        <p className="text-sm text-gray-300">Each account is subject to 300 API requests per minute. Exceeding this limit returns HTTP 429. Systematic abuse (scraping, bot traffic, credential sharing) will result in immediate account suspension.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-green-400 mb-3">6. Limitation of Liability</h2>
        <p className="text-sm text-gray-300">TO THE MAXIMUM EXTENT PERMITTED BY LAW, WORLDSTATE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, ARISING FROM YOUR USE OF OR RELIANCE ON ANY INFORMATION PROVIDED BY THE SERVICE.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-green-400 mb-3">7. Termination</h2>
        <p className="text-sm text-gray-300">You may terminate your account at any time via <code className="text-green-400">DELETE /auth/me</code>. We reserve the right to suspend or terminate access for violations of these Terms with 24 hours' notice (immediate suspension for security violations).</p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-green-400 mb-3">8. Governing Law</h2>
        <p className="text-sm text-gray-300">These Terms are governed by the laws of Delaware, USA. Any disputes shall be resolved by binding arbitration in accordance with the AAA Commercial Arbitration Rules.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-green-400 mb-3">9. Contact</h2>
        <p className="text-sm text-gray-300">Legal inquiries: <span className="text-green-400">legal@worldstate.ai</span></p>
      </section>
    </div>
  )
}
